#!/usr/bin/env bash

cd "$(dirname "${BASH_SOURCE}")"

git pull origin master

function syncDotfiles() {
	rsync --exclude ".git/" --exclude ".DS_Store" --exclude "bootstrap.sh" \
		--exclude "README.md" --exclude "LICENSE-MIT.txt" -avh --no-perms . ~
	source ~/.bash_profile
}

function backup() {
  echo "backup TBD"
}

if [ "$1" == "--force" -o "$1" == "-f" ]; then
	syncDotfiles
else
	read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
	echo
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		syncDotfiles
	fi
fi
unset syncDotfiles
unset backup
