#!/bin/bash

function iterm_run() {
  osascript \
    -e 'activate application "iTerm"' \
    -e "tell application \"System Events\" to tell process \"iTerm\" to keystroke \"$1\"" \
    -e 'tell application "System Events" to tell process "iTerm" to key code 52'
}

function iterm_new_v_pane() {
  osascript \
    -e 'activate application "iTerm"' \
    -e 'tell application "System Events" to tell process "iTerm" to keystroke "d" using {shift down, command down}' \
}

function iterm_new_h_pane() {
  osascript \
    -e 'activate application "iTerm"' \
    -e 'tell application "System Events" to tell process "iTerm" to keystroke "d" using command down' \
}

function iterm_prev_pane() {
  osascript \
    -e 'activate application "iTerm"' \
    -e 'tell application "System Events" to tell process "iTerm" to key code 123 using {shift down, command down}' \
}

function iterm_next_pane() {
  osascript \
    -e 'activate application "iTerm"' \
    -e 'tell application "System Events" to tell process "iTerm" to key code 124 using {shift down, command down}' \
}

function load() {
  setproj $1
  cd $1
  bot "Load project config"
  if [ -f .project ]
  then
    source .project
    load
    bot "Successful"
    alias load="bot \"Project already loaded\""
  else
    bot "No project file"
  fi
}
