#!/usr/bin/env bash
echo "👾👾👾👾   Update brew"
brew update

echo "👾👾👾👾   Install bash-completion"
brew install bash-completion

echo "👾👾👾👾   Install ngrep"
brew install ngrep

echo "👾👾👾👾   Install tree"
brew install tree

echo "👾👾👾👾   Install wget"
brew install wget

echo "👾👾👾👾   Install git-wtf"
wget http://git-wt-commit.rubyforge.org/git-wtf -O ~/bin/git-wtf
chmod +x ~/bin/git-wtf
