#!/usr/bin/env bash
echo "👾👾👾👾  <- dancing aliens ::: Update brew"
brew update

echo "👾👾👾👾  <- dancing aliens ::: Install bash-completion"
brew install bash-completion

echo "👾👾👾👾  <- dancing aliens ::: Install ngrep"
brew install ngrep

echo "👾👾👾👾  <- dancing aliens ::: Install tree"
brew install tree

echo "👾👾👾👾  <- dancing aliens ::: Install wget"
brew install wget

echo "👾👾👾👾  <- dancing aliens ::: Install git-wtf"
wget http://git-wt-commit.rubyforge.org/git-wtf -O ~/bin/git-wtf
chmod +x ~/bin/git-wtf
