#!/usr/bin/env bash
echo "👾👾   Update brew"
brew update

echo "👾👾   Install bash-completion"
brew install bash-completion

echo "👾👾   Install ngrep"
brew install ngrep

echo "👾👾   Install tree"
brew install tree
