#!/usr/bin/env bash

function echomsg {
  echo -e "👾👾👾👾  <- dancing aliens: \033[33m$1\033[39m"
}

echomsg "UPDATE brew"
brew update

echomsg "INSTALL bash-completion"
brew install bash-completion

echomsg "INSTALL ngrep"
brew install ngrep

echomsg "INSTALL tree"
brew install tree

echomsg "INSTALL wget"
brew install wget

echomsg "INSTALL git-wtf"
wget http://git-wt-commit.rubyforge.org/git-wtf -O ~/bin/git-wtf
chmod +x ~/bin/git-wtf

echomsg "INSTALL git-flow"
brew install git-flow

unset echomsg
